name: Test 3x-ui bot installation

on:
    push:
        branches:
            - main

jobs:
    test-installation-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Update and upgrade
              run: |
                  sudo apt-get update
                  sudo apt-get upgrade -y

            - name: Install Docker dependencies
              run: sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

            - name: Add Docker GPG Key and Repository
              run: |
                  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
                  echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

            - name: Install Docker
              run: sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io

            - name: Run install.sh
              run: |
                  chmod +x install.sh
                  ./install.sh
