name: Test 3x-ui bot installation

on:
    push:
        branches:
            - main

jobs:
    test-installation-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker
              uses: docker/setup-docker@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Run install.sh
              run: |
                  chmod +x install.sh
                  ./install.sh
